### ISSUE TITLE
Instalation and configuration for starters

### ISSUE THREAD

**Issue by guigsilva** [decidim/decidim-bulletin-board#214]
Hello!

We try to install this cloning the repository and following the readme  for server (https://github.com/decidim/decidim-bulletin-board/blob/develop/bulletin_board/server/README.md) but the rails db:create gives us error on PSQL authentication. We alredy have a decidim working and try to put in application.yml the credentials for a DB to bulletin-board but don´t work.

We search the decidim documentation but no lucky there too...

Can anyone give us some light on this?

We are trying to install on the same machine as decidim, this is ok?

We have a ubuntu 20.04 as OS 

Thanks 
Guilherme

**Comment by andreslucena** [comment]
Hello @guigsilva
Thanks for the report. Indeed there are lots of docs missing. At the moment this is still a Work In Progress and we should reflect that in the README until it's audited and documented.

**Comment by microstudi** [comment]
This should be covered #215

**Comment by andreslucena** [comment]
Closing as fixed by https://github.com/decidim/decidim-bulletin-board/pull/215
