### ISSUE TITLE
Add `decidim` user to published rubygems

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim-bulletin-board#238]
Related to #210 

No one active in the Decidim maintenance has access to the gems related to this repository: 

https://rubygems.org/gems/decidim-bulletin_board
https://rubygems.org/gems/voting_schemes-electionguard
https://rubygems.org/gems/voting_schemes-dummy

For managing these access there's the `decidim` generic user: https://rubygems.org/profiles/decidim

It needs to have access.

**Comment by ahukkanen** [comment]
Access has been already granted to `decidim` and `mainio`, so this is resolved.
