### ISSUE TITLE
Document README.md for gems

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim-bulletin-board#246]
At the moment it has the typical files with the `TODO: Delete this and the text above, and describe your gem`. 

We should modify that

https://github.com/decidim/decidim-bulletin-board/blob/b6519e6bd01037ece99083432bee06851afdfaa5/bulletin_board/ruby-client/README.md
https://github.com/decidim/decidim-bulletin-board/blob/b6519e6bd01037ece99083432bee06851afdfaa5/voting_schemes/electionguard/ruby-adapter/README.md
https://github.com/decidim/decidim-bulletin-board/blob/b6519e6bd01037ece99083432bee06851afdfaa5/voting_schemes/dummy/ruby-adapter/README.md

**Comment by microstudi** [comment]
still relevant
