### ISSUE TITLE
Allow configuring different ActiveStorage providers 

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim-bulletin-board#261]
On #253 the bulletin board app was changed so that in production environment you use AWS S3 by default. This is against https://decidim.org/contract

We need to provide a FLOSS solution as first option, for instance by using Docker volumes or clarifying on the documentation that you can use [Minio](https://hub.docker.com/r/minio/minio/) or other alternative services that implement the S3 protocol.

**Comment by microstudi** [comment]
@andreslucena I see that this commit allows to specify the provider from an ENV var https://github.com/decidim/decidim-bulletin-board/commit/ce5d4b1a0cd576c62c517cb95d6af62961686a71

Although is not as complete as the Decidim side (allowing also GCS and Azure) it should cover the basics

**Comment by andreslucena** [comment]
Ah ok, didn't catch that commit. It works for me, closing this issue.
