### ISSUE TITLE
Broken CI: template is not valid 

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim-bulletin-board#262]
The CI is broken after the last commits.

1. [[CI] Server - Unit tests](https://github.com/decidim/decidim-bulletin-board/runs/5705120399?check_suite_focus=true) 

> Error: .github/workflows/server-workflow.yml (Line: 161, Col: 16):
> Error: The template is not valid. .github/workflows/server-workflow.yml (Line: 161, Col: 16): hashFiles('voting_schemes/electionguard/python-wrapper/**') failed. Fail to hash files under directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board'
> 

2. In [[CI] Server - E2E tests](https://github.com/decidim/decidim-bulletin-board/runs/5705120379?check_suite_focus=true)

> (...)
> Bundle complete! 6 Gemfile dependencies, 61 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> cd voting_schemes/electionguard/python-wrapper && make install
> make[1]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper'
> python3 -m pip install --upgrade pip
> Requirement already satisfied: pip in /root/.pyenv/versions/3.8.11/lib/python3.8/site-packages (21.1.1)
> Collecting pip
>   Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 21.1.1
>     Uninstalling pip-21.1.1:
>       Successfully uninstalled pip-21.1.1
> WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
> Successfully installed pip-22.0.4
> cd ../electionguard-python && make environment build
> make[2]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> 🔧 ENVIRONMENT SETUP
> make install-gmp
> make[3]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> 📦 Install gmp
> Operating System identified as Linux
> make install-gmp-linux
> make[4]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> 🐧 LINUX INSTALL
> sudo apt-get install libgmp-dev
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following additional packages will be installed:
>   libgmp10 libgmpxx4ldbl
> Suggested packages:
>   gmp-doc libgmp10-doc
> The following packages will be upgraded:
>   libgmp-dev libgmp10 libgmpxx4ldbl
> 3 upgraded, 0 newly installed, 0 to remove and 74 not upgraded.
> Need to get 903 kB of archives.
> After this operation, 1024 B of additional disk space will be used.
> Do you want to continue? [Y/n] Abort.
> make[4]: *** [Makefile:55: install-gmp-linux] Error 1
> make[4]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> make[3]: *** [Makefile:34: install-gmp] Error 2
> make[3]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> make[2]: *** [Makefile:13: environment] Error 2
> make[2]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> make[1]: *** [Makefile:9: install] Error 2
> make[1]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper'
> make: *** [voting_schemes/electionguard/makefile.mk:93: install_electionguard_python_wrapper] Error 2
> Error: Process completed with exit code 2.
> (...)

**Comment by ahukkanen** [comment]
I bumped into the same issue at #251 and I temporarily enabled the debug logging for the jobs.

I get the following output for this:

```
##[debug]Match Pattern: voting_schemes/electionguard/python-wrapper/**
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::implicitDescendants 'true'
##[debug]::debug::omitBrokenSymbolicLinks 'true'
##[debug]::debug::Search path '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper'
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper
##[debug]Skip directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper'.
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.devcontainer
##[debug]Skip directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.devcontainer'.
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.devcontainer/Dockerfile
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.devcontainer/devcontainer.json
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.flake8
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.github
##[debug]Skip directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.github'.
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.github/workflows
##[debug]Skip directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.github/workflows'.
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.github/workflows/python-app.yml
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.gitignore
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv
##[debug]Skip directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv'.
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/.gitignore
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/.project
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin
##[debug]Skip directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin'.
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/activate
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/activate.csh
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/activate.fish
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/activate.nu
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/activate.ps1
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/activate_this.py
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/black
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/blackd
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/deactivate.nu
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/f2py
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/f2py3
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/f2py3.8
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/flake8
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/jsonschema
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pip
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pip-3.8
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pip3
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pip3.8
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/py.test
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pycodestyle
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pyflakes
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/pytest
##[debug]/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/python
##[debug]Error: EACCES: permission denied, stat '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/python'
##[debug]    at Object.statSync (node:fs:1536:3)
##[debug]    at /home/runner/runners/2.289.1/bin/hashFiles/index.js:1593:24
##[debug]    at Generator.next (<anonymous>)
##[debug]    at fulfilled (/home/runner/runners/2.289.1/bin/hashFiles/index.js:1539:58) {
##[debug]  errno: -13,
##[debug]  syscall: 'stat',
##[debug]  code: 'EACCES',
##[debug]  path: '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper/.venv/bin/python'
##[debug]}
##[debug]STDOUT/STDERR stream read finished.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Finished process 6871 with exit code 1, and elapsed time 00:00:00.1080903.
```

So, the underlying reason is because the system cannot access some of the files to be hashed in the `.venv` folder of the python-wrapper.

I had similar issues before which I fixed by avoiding having the `.venv` folder in the cache hash.

I'll investigate further if I can exclude the `.venv` folder from the cache hash calculation.

**Comment by ahukkanen** [comment]
Yep, the cache hash issue can be fixed by excluding the `.venv` folder from the hash calculation as so:
https://github.com/decidim/decidim-bulletin-board/pull/251/commits/e10bf70cd2c76f6f530475b0faf77896914b9629

This is part of #251.

The other issue in the CI should be also fixed by #251. It is due to apt-get yes prompt from the user which causes the command to stall. It can be fixed either by adding the `-y` flag to the apt-get commands or directly into the container as I did with the Ruby 3 container image:
https://github.com/decidim/decidim-bulletin-board/pull/251/commits/ce3c199c5cb8acde4c381ee35fa99fd12b0107a3

**Comment by ahukkanen** [comment]
I still have one related issue at #251 which is also similar to the python-wrapper issue.

The JS cache hash calculation fails for the E2E tests because it cannot access files within the `bulletin_board/server/cypress/downloads` folder. I have tried similar tricks as with the python-wrapper but it doesn't seem to work due to the glob pattern `**/package-lock.json`. I think this pattern tries to access all folders prior to the exclusion pattern being applied.

I'll continue investigation on that.

**Comment by ahukkanen** [comment]
That last issue I just fixed by deleting the cypress downloads folder after the artifacts have been uploaded from there:
https://github.com/decidim/decidim-bulletin-board/pull/251/commits/e16144eefe66048d62ec6c778520dc789a7b096e
